import pandas as pd
from notebook.consumo_usuario import consumir_api_tabla_usuarios
from notebook.limpieza_usuarios import limpiar_datos
from notebook.transformacion_usuario import transformar_datos

datos_tabla_usuarios=consumir_api_tabla_usuarios()
print(datos_tabla_usuarios)

data_frame_usuarios= pd.DataFrame(datos_tabla_usuarios)
data_frama_limpio_usuarios=limpiar_datos(data_frame_usuarios)

agrupaciones=transformar_datos(data_frama_limpio_usuarios)
print(agrupaciones)
